apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# postgres
- postgres/statefulset.yaml
- postgres/service.yaml
# mongo
- mongo/statefulset.yaml
- mongo/service.yaml
# redis
- redis/statefulset.yaml
- redis/service.yaml
# books
- books/deployment.yaml
- books/service.yaml
# reviews
- reviews/deployment.yaml
- reviews/service.yaml
# votes
- votes/deployment.yaml
- votes/service.yaml
# frontend
- frontend/deployment.yaml
- frontend/service.yaml
